name:                alphascript
version:             0.1.0.0
author:              Group 22

extra-source-files:
- README.md

description:
  This project is a compiler for a simple programming language designed 
  for educational purposes, and may not be suitable for production use. 
  While the language it compiles is simple, it covers fundamental 
  concepts such as variables and functions.

dependencies:
- base
- parsec
- sprockell
- QuickCheck
- containers
- directory

library:
  source-dirs: src

executables:
  alphascript-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - alphascript
