# Resolver decides package versions
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/4.yaml

# User packages to be built
packages:
- .

# Pull Sprockell lib from GitHub
extra-deps:
- github: bobismijnnaam/sprockell
  commit: 3872ca567673f994170f49bbf7b1eaadf999af10